---
title: "module4_workshop3"
author: "Madhumita Kabade"
date: "2025-04-08"
output: html_document
---

#reading the data file
its in the working directory now, and now you are asking R to read it for further analysis. read.csv cannot open excel files, so read_excel(). 
```{r}
library(janitor)
getwd()#before loading data always do this.
data <- read_csv("../data/shark_data_workshop3.csv")
view(data)
as_tibble(data)
```

#cleaning and filtering data and following ben
```{r}
str(data)
shark_program <- read_csv("../data/shark_data_workshop3.csv") |>
  row_to_names(row_number = 2, remove_rows_above = FALSE) |> # will make the row number 2 as the column name, thats why row to names
  clean_names() #makes all the names lower case
head(shark_program) #shows only the first six rows of your data set.

  



```


```{r}
shark_catch <- 
  shark_program |>
  select(area | contains("shark")) |> #selecting those values of column area that have shark samples.
  row_to_names(row_number = 1) |> #getting years from row 1 as column(names)
  rename(Area = 1) |> #renames the column 1 as area, this function only works for columns not for rows
  mutate(across(-c(Area), as.numeric)) #mutate is ether making a new column, or modifying the existing ones. across means the function will be applied across all the columns. -c(area) means that function will be applied across all the columns except area. as numeric is making all the columns numeric except area.
  
turtle_catch <- 
  shark_program |>
  select(area | contains("turtle")) |>
  row_to_names(row_number = 1) |>
  rename(Area = 1) |>
  mutate(across(-c(Area), as.numeric)) 

head(shark_catch)
head(turtle_catch)
```

#pivot longer
we are doing data reshaping turning a wide table format into a long one.    
```{r}

shark_catch_long <- 
shark_catch |>
  pivot_longer(!Area, names_to = "Year", values_to = "Nos") #names_to = year - making all the column names into another column and naming the column as year. values_to putting all the values under one column named nos


turtle_catch_long <- 
  turtle_catch |>
  pivot_longer(!Area, names_to = "Year", values_to = "Nos")
view(shark_catch_long)
view(turtle_catch_long)
```
#make stat tibbles

```{r}
shark_stats <- 
shark_catch_long |>
  filter(Area != "Grand Total") |> #removes all the rows with grand total as their value. filter is only used for rows, not for columns and if using for columns you would have to use select or remove.
  group_by(Year) |> # will calculate the stats for each value of year.
  summarise(Mean = mean(Nos, na.rm = TRUE),
            SD = sd(Nos, na.rm = TRUE)) |>
  mutate(Year = as.numeric(Year)) |>
  mutate(Taxa = "Sharks")

turtle_stats <- 
turtle_catch_long |>
  filter(Area != "Grand Total") |>
  group_by(Year) |>
  summarise(Mean = mean(Nos, na.rm = TRUE),
            SD = sd(Nos, na.rm = TRUE)) |>
  mutate(Year = as.numeric(Year)) |>
  mutate(Taxa = "Turtles")

combine_stats <- 
  bind_rows(shark_stats, turtle_stats)

view(shark_stats)
view(turtle_stats)
view(combine_stats)
```

#creating the plot
```{r}
ggplot(data = combine_stats, aes(x =Year, y = Mean, fill = Taxa, shape = Taxa), colour = "black") +
  geom_line() +
  geom_pointrange(aes(ymin = Mean - SD, ymax = Mean + SD)) +
    scale_shape_manual(values = c(23, 24))
```


